<?php
/*
Language File for amacube

This file is part of the amacube Roundcube plugin
Copyright (C) 2013, Alexander Köb <nerdkram@koeb.me>

Licensed under the GNU General Public License version 3. 
See the COPYING file for a full license statement.          

*/
$labels = array();
$labels['page_title'] = 'Amavis WBlist';
$labels['menu_button'] = 'Amavis WBlist';
$labels['box_title'] = 'Amavis White / Black List';
$labels['no_entries'] = 'No Entries in WBlist policy';

$labels['section_wblist_add'] = 'Add Entry';

$messages = array();
$messages['error_wblist_add_address'] = 'Unable to add empty wblist entry';
$messages['error_wblist_add_policy'] = 'Unable to add Invalid Policy';
$messages['error_wblist_delete'] = 'Unable to delete wblist entry';
?>